# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # manually set db_pool, separate from threads, because sidekiq
  pool: <%= ENV.fetch("DB_POOL") { 20 } %>

test:
  <<: *default
  database: tranzito_utils_test
